### ISSUE TITLE
"Statically generated websites (...) don't scale beyond a few pages."

### ISSUE THREAD

**Issue by yann-yinn** [zeit/spr-landing#5]
Hello ! 

> "Statically generated websites (...) don't scale beyond a few pages."

(from https://spr-landing.zeit.sh/ )

This sentence is misleading : it gives the false impression than "Statically generated websites" can only handle 5 or 20 pages; which is wrong; they can handle, with decent build times, hundreds or thousands of pages.

**Comment by paulogdm** [comment]
Thanks for the feedback! I have relayed.

**Comment by paulogdm** [comment]
First, I understand how the phrasing of our statement can be "aggressive".
The problem with fully static websites is the form of how collaborative work and continuous delivery operation with each other. We observe this with our [docs repository](github.com/zeit/docs). It works just fine with a few contributors and not many PRs each day. Every PR + commits is a new deployment. But if you have a blog or a press site, do you really need a dynamic solution to deliver fresh content to your users? Do you really need a heavy-backend piping content again and again to your clients?

We have a few models for sites that can have dynamic content:
- New content = new deploy. Doesn't scale well as I quoted above.
- New content = DB content is added. API needed here. You can use custom-tailored cache solutions.
- CMS in the backend = good! But you don't need to query your DB aggressively for each change. So a caching layer is needed to improve performance and usability.
SPR is that cache layer. Instead of you considering that event in your client or server, let the cache layer control the freshness of content for you with flags!
That is why this is a game-changer. You can query expensive stuff in the background while still serving content in a few ms. Let the appropriate layer care about content while you produce those or increment your code. All of that with not much effort!

**Comment by rauchg** [comment]
@yann-yinn "can only handle 5 or 20 pages" was added by you. I didn't mention any specific numbers.

I stand by the original statement that re-building everything from scratch, making API calls to diff a database from your local build cache, won't scale beyond a few pages. Maybe a few hundred is possible, if you're willing to wait a long time. But the whole point of this example is to show that you *don't* have to wait a long time.

**Comment by yann-yinn** [comment]
> Maybe a few hundred is possible

For sure :  i'm currently building 1000 products in 100 milliseconds. With CDN deployment included, the whole process takes less than one minute. So it scales beyond a few pages and i would not call this "a long time" ^^

Your demonstration is cool, just wanted to show that static generators are not that bad.
